services:
  site:
    build:
      context: .
    ports:
      - 8080:80
    networks:
      - net
    depends_on:
      - db
    volumes:
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      AUTH_KEY: ${AUTH_KEY}
      AUTH_SALT: ${AUTH_SALT}
      LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      NONCE_KEY: ${NONCE_KEY}
      NONCE_SALT: ${NONCE_SALT}
      SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      WP_HOME: http://localhost:8080
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - net
    ports:
      - "3306:3306"

networks:
  net:
    driver: bridge

volumes:
  db_data:
